name: autofix.ci

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: voidzero-dev/setup-vp@3754dd7dbdb32bd8f6d28b6043de13ad3a75f21f # v1.21.1
        with:
          node-version: v26.10.0
          cache: true
          run-install: |
            - cwd: .

      - name: Fix lint issues
        run: pnpm run lint:fix

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
        with:
          commit-message: "chore: apply automated updates"
